### PR TITLE
Fix gcc-10 compiler warnings. Fixes #33

### LINKED ISSUE #33: 1.0.7: gcc 10 compile time warnings
```
sctp.c: In function 'protocol_sctp_connect':
sctp.c:196:12: warning: unused variable 'off' [-Wunused-variable]
  196 |  const int off = 0;
      |            ^~~
sctp.c:195:12: warning: unused variable 'len' [-Wunused-variable]
  195 |  socklen_t len;
      |            ^~~
udp.c: In function 'protocol_udp_listen':
udp.c:234:7: warning: unused variable 'hostname' [-Wunused-variable]
  234 |  char hostname[NI_MAXHOST];
      |       ^~~~~~~~
parse.c:333:1: warning: 'print_workorder_t' defined but not used [-Wunused-function]
  333 | print_workorder_t(workorder_t *w) {
      | ^~~~~~~~~~~~~~~~~
parse.c:280:1: warning: 'print_symbols' defined but not used [-Wunused-function]
  280 | print_symbols(struct symbol *list) {
      | ^~~~~~~~~~~~~
ssl.c: In function 'file_present':
ssl.c:133:6: warning: unused variable 'err' [-Wunused-variable]
  133 |  int err;
      |      ^~~
ssl.c: In function 'protocol_ssl_accept':
ssl.c:226:18: warning: unused variable 'name' [-Wunused-variable]
  226 |  struct sockaddr name;
      |                  ^~~~
ssl.c:224:17: warning: unused variable 'ssl_p' [-Wunused-variable]
  224 |  ssl_private_t *ssl_p = (ssl_private_t *) p->_protocol_p;
      |                 ^~~~~
ssl.c: In function 'protocol_ssl_read':
ssl.c:361:20: warning: unused variable 'flowop_options' [-Wunused-variable]
  361 |  flowop_options_t *flowop_options = (flowop_options_t *) options;
      |                    ^~~~~~~~~~~~~~
ssl.c:360:8: warning: unused variable 'host' [-Wunused-variable]
  360 |  char *host = p->host[0] == '\0' ? p->host : "Unknown";
      |        ^~~~
ssl.c:358:6: warning: unused variable 'status' [-Wunused-variable]
  358 |  int status = 1;
      |      ^~~~~~
ssl.c:357:6: warning: unused variable 'bufsize' [-Wunused-variable]
  357 |  int bufsize = size * 10;
      |      ^~~~~~~
ssl.c:356:6: warning: unused variable 'i' [-Wunused-variable]
  356 |  int i;
      |      ^
ssl.c: In function 'protocol_ssl_write':
ssl.c:377:20: warning: unused variable 'flowop_options' [-Wunused-variable]
  377 |  flowop_options_t *flowop_options = (flowop_options_t *) options;
      |                    ^~~~~~~~~~~~~~
ssl.c:376:6: warning: unused variable 'bufsize' [-Wunused-variable]
  376 |  int bufsize = size * 10;
      |      ^~~~~~~
ssl.c:375:6: warning: unused variable 'i' [-Wunused-variable]
  375 |  int i;
      |      ^
ssl.c:374:6: warning: unused variable 'status' [-Wunused-variable]
  374 |  int status = 1;
      |      ^~~~~~
ssl.c:373:8: warning: unused variable 'host' [-Wunused-variable]
  373 |  char *host = p->host[0] == '\0' ? p->host : "Unknown";
      |        ^~~~
ssl.c: In function 'ssl_fini':
ssl.c:506:17: warning: unused variable 'ssl_p' [-Wunused-variable]
  506 |  ssl_private_t *ssl_p = (ssl_private_t *) p->_protocol_p;
      |                 ^~~~~
At top level:
ssl.c:94:1: warning: 'id_function' defined but not used [-Wunused-function]
   94 | id_function(void)
      | ^~~~~~~~~~~
ssl.c:84:1: warning: 'locking_function' defined but not used [-Wunused-function]
   84 | locking_function(int mode, int n, char *file, int line)
      | ^~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by realneel**
I don't have ssl installed. Will try to install a VM to test and report back.

### CODE REVIEW

File: src/parse.c [hunk 1]
```diff
@@ -978,7 +983,9 @@ parse_app_profile(char *filename)
 	buffer[size - 1] = '\0';
 
 	parse(buffer, &list);
-	/* print_symbols(list.next); */
+#ifdef DEBUG
+	print_symbols(list.next); */
+#endif /* DEBUG */
```
Comment (tuexen) [inline src/parse.c:988]: Remove trailing `*/`.

File: src/ssl.c [hunk 2]
```diff
@@ -357,15 +354,11 @@ protocol_ssl_disconnect(protocol_t * p)
...
-	int status = 1;
 	ssl_private_t *ssl_p = (ssl_private_t *) p->_protocol_p;
-	char *host = p->host[0] == '\0' ? p->host : "Unknown";
-	flowop_options_t *flowop_options = (flowop_options_t *) options;
 
-	uperf_debug("ssl - Reading %d bytes from %s:%d\n", size, host,
-		p->port);
+	uperf_debug("ssl - Reading %d bytes from %s:%d\n", size,
+            p->host[0] == '\0' ? p->host : "Unknown",
+            p->port);
```
Comment (tuexen) [inline src/ssl.c:361]: I guess this should read:
```
p->host[0] == '\0' ? "Unknown" : p->host,
```

File: src/ssl.c [hunk 3]
```diff
@@ -375,10 +368,6 @@ protocol_ssl_write(protocol_t * p, void *buffer, int size, void *options)
 {
 	ssl_private_t *ssl_p = (ssl_private_t *) p->_protocol_p;
 	char *host = p->host[0] == '\0' ? p->host : "Unknown";
-	int status = 1;
-	int i;
-	int bufsize = size * 10;
-	flowop_options_t *flowop_options = (flowop_options_t *) options;
 
 	uperf_debug("ssl - Writing %d bytes to %s:%d\n", size, host,
 		p->port);
```
Comment (tuexen) [inline src/ssl.c:373]: I guess you need to do the same dance as above.

File: src/ssl.c [hunk 4]
```diff
@@ -375,10 +368,6 @@ protocol_ssl_write(protocol_t * p, void *buffer, int size, void *options)
 {
 	ssl_private_t *ssl_p = (ssl_private_t *) p->_protocol_p;
 	char *host = p->host[0] == '\0' ? p->host : "Unknown";
```
Comment (tuexen) [inline src/ssl.c:370]: Same dance as above?
