### PR TITLE
Reset connections in flowops if we connect/disconnect (Fixes #24)

### LINKED ISSUE #24: Fix failing test_send_recv.xml
After we re-enabled tests, we see that test_send_recv.xml is failing.

### PR DESCRIPTION
**Pull request by realneel**

### CODE REVIEW

File: src/flowops_library.c [hunk 1]
```diff
@@ -172,8 +172,13 @@ flowop_connect(strand_t *sp, flowop_t *fp)
 	datap->p_id = fp->p_id;
 
 	error = datap->connect(datap, &fp->options);
-	if (error == UPERF_SUCCESS)
+	if (error == UPERF_SUCCESS) {
```
Comment (portante) [inline src/flowops_library.c:175]: Looks like a tabs vs spaces formatting problem.

Comment (realneel) [reply src/flowops_library.c:175]: thanks for catching that. Fixed it.

**Comment by tuexen** [comment]
Looks good to me, except that this mixes whitespace changes with functional changes.
